---
- name: Instala o puppet-agent nos RHEL7
  yum:
    name: puppet-agent
    state: present
  when: ansible_os_family == "RedHat"

- name: Instala o puppet-agenet no debian
  apt:
    name: puppet-agent
    state: present
    update-cache: yes
  when: ansible_os_family == "Debian"
