---
- block:


  - name: Instala do apache no Redhat
    yum:
      name: httpd
      state: present
  
  - name: Reinicia o apache
    service:
      name: httpd
      state: restarted

  when: ansible_distribution == "CentOs"

- block:

  - name: Instala do apache no debian
    yum:
      name: apache2
      state: present

  - name: Reinicia o apache
    service:           
      name: apache2      
      state: restarted
  

  when: ansible_distribution == "Ubuntu"
 
